name: Sponsor Generator

on:
  schedule: [{ cron: '0 0 * * *' }]
  workflow_dispatch:

jobs:
  autoflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Curl light
        run: |-
          curl -o './static/temp-sponsor-light.png' 'https://readme-wizard.lobehub.com/api/sponsor'
          if [ $? -eq 0 ] && [ -s './static/temp-sponsor-light.png' ]; then
            mv './static/temp-sponsor-light.png' './static/sponsor-light.png'
          else
            echo "Curl failed or file is empty, keeping the original sponsor-light.png"
          fi

      - name: Curl dark
        run: |-
          curl -o './static/temp-sponsor-dark.png' 'https://readme-wizard.lobehub.com/api/sponsor?themeMode=dark'
          if [ $? -eq 0 ] && [ -s './static/temp-sponsor-dark.png' ]; then
            mv './static/temp-sponsor-dark.png' './static/sponsor-dark.png'
          else
            echo "Curl failed or file is empty, keeping the original sponsor-dark.png"
          fi

      - name: Commit changes
        run: |-
          git diff
          git config --global user.name "lobehubbot"
          git config --global user.email "i@lobehub.com"
          git add .
          git commit -m "🤖 chore: Auto update sponsor list" || exit 0
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
